---
- name: Jenkins Agent Setup
  hosts: localhost
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  vars_files:
    - vars/all.yml
  tasks:
    - include_tasks: tasks/common.yml
    - include_tasks: tasks/cloudwatch-agent.yml
    - include_tasks: tasks/go.yml
    - include_tasks: tasks/docker.yml
    - include_tasks: tasks/git.yml
    - include_tasks: tasks/terraform.yml
    - include_tasks: tasks/jenkins.yml
